services:
    vse.abbc3.manager:
        class: vse\abbc3\core\manager
        arguments:
            - @user
    vse.abbc3.listener:
        class: vse\abbc3\event\listener
        tags:
            - { name: event.listener }
