services:
    vse.abbc3.parser:
        class: vse\abbc3\core\parser
        arguments:
            - @user
    vse.abbc3.bbcodes:
        class: vse\abbc3\core\bbcodes
        arguments:
            - @dbal.conn
            - @user
            - %core.root_path%
    vse.abbc3.acp_manager:
        class: vse\abbc3\core\acp_manager
        arguments:
            - @dbal.conn
            - @request
            - @user
    vse.abbc3.listener:
        class: vse\abbc3\event\listener
        arguments:
            - @vse.abbc3.parser
            - @vse.abbc3.bbcodes
            - @controller.helper
            - @template
            - @user
            - %core.root_path%
        tags:
            - { name: event.listener }
    vse.abbc3.acp_listener:
        class: vse\abbc3\event\acp_listener
        arguments:
            - @vse.abbc3.acp_manager
            - %core.root_path%
        tags:
            - { name: event.listener }
    vse.abbc3.wizard:
        class: vse\abbc3\controller\wizard
        arguments:
            - @controller.helper
            - @request
            - @template
            - @user
            - %core.root_path%
