services:
    vse.abbc3.parser:
        class: vse\abbc3\core\parser
        arguments:
            - @user
    vse.abbc3.listener:
        class: vse\abbc3\event\listener
        tags:
            - { name: event.listener }
